// MixpanelAnalytics.swift
// SourceBible
//
// Live Mixpanel implementation — compiled in ALL build configurations.
// Consent-gated lazy init (PDR D3/D4): the SDK is NOT loaded at construction.
// enable() initializes it (only after consent ON); until then every method no-ops
// and nothing is sent. disable() opts out. Prod is opt-in (default OFF); beta/dev
// default ON. Token per build chosen by isTestFlight (PDR D5).
//
// Outside this file: zero direct Mixpanel usage; all calls go through AnalyticsService.
//
// Swift 6 note:
//   MixpanelInstance is not Sendable (Swift-5 SDK, uses DispatchQueue internally).
//   We mark this wrapper @unchecked Sendable and accept the responsibility:
//   every call goes to Mixpanel's own track/identify APIs, which are thread-safe
//   via their internal trackingQueue.
//
// Tokens are read from AnalyticsConfiguration (auto-generated by the
// "Generate Analytics Token" build phase from Config/Secrets.xcconfig).

import Mixpanel
import Foundation

final class MixpanelAnalytics: AnalyticsService, @unchecked Sendable {

    // MARK: - Singleton

    static let shared = MixpanelAnalytics()

    /// True once the SDK has been initialized (after consent → enable()).
    /// Until then every method is a no-op: nothing is sent, the SDK isn't even loaded.
    // swiftlint:disable:next nonisolated_unsafe
    private nonisolated(unsafe) var started = false

    // MARK: - Init

    // SDK is NOT initialized here. Initialization is deferred to enable(), called only
    // after consent is ON (PDR D4: prod is opt-in, so nothing must load pre-consent).
    private init() {}

    // MARK: - Consent lifecycle

    /// Initialize the Mixpanel SDK and opt in. Call only after consent is ON. Idempotent.
    func enable() {
        if started {
            Mixpanel.mainInstance().optInTracking()
            return
        }
        let token = Self.resolvedToken
        guard !token.isEmpty else {
            print("[MixpanelAnalytics] ⚠️ Token empty for this build — fill the matching MIXPANEL_*_TOKEN in Config/Secrets.xcconfig and rebuild")
            return
        }
        // trackAutomaticEvents: false — we own the full event taxonomy (spec §Event Taxonomy).
        Mixpanel.initialize(token: token, trackAutomaticEvents: false)
        #if DEBUG
        // Spec §Тестування до TestFlight: log every event to Xcode console in DEBUG.
        Mixpanel.mainInstance().loggingEnabled = true
        #endif
        started = true
    }

    /// Consent revoked: opt out so the SDK drops queued + future events. No-op if never started.
    func disable() {
        guard started else { return }
        Mixpanel.mainInstance().optOutTracking()
    }

    // MARK: - AnalyticsService

    func track(_ event: AnalyticsEvent) {
        guard started else { return }
        let (name, props) = event.nameAndProperties
        let mpProps = props.compactMapValues { $0 as? MixpanelType }
        Mixpanel.mainInstance().track(event: name, properties: mpProps)

        #if DEBUG
        // Spec §Тестування до TestFlight: flush immediately in DEBUG so events
        // appear in Mixpanel Live / Events within seconds (no batch wait).
        Mixpanel.mainInstance().flush()
        #endif
    }

    func identify(distinctId: String) {
        guard started else { return }
        Mixpanel.mainInstance().identify(distinctId: distinctId)
    }

    func flush() {
        guard started else { return }
        Mixpanel.mainInstance().flush()
    }

    // MARK: - Helpers

    /// Token for this build (PDR D5): DEBUG → dev; Release → beta (TestFlight) vs prod (App Store).
    static var resolvedToken: String {
        #if DEBUG
        return AnalyticsConfiguration.mixpanelDevToken
        #else
        return isTestFlight ? AnalyticsConfiguration.mixpanelBetaToken
                            : AnalyticsConfiguration.mixpanelProdToken
        #endif
    }

    /// True when running from TestFlight (sandboxReceipt) or Simulator.
    static var isTestFlight: Bool {
        #if targetEnvironment(simulator)
        return true
        #else
        return Bundle.main.appStoreReceiptURL?.lastPathComponent == "sandboxReceipt"
        #endif
    }
}
