// MixpanelAnalytics.swift
// SourceBible
//
// Live Mixpanel implementation — compiled in ALL build configurations.
// Gating is purely at runtime: consent toggle (analyticsEnabled) ON → use this;
// OFF → NoopAnalytics. No #if BETA guard needed (PDR-Analytics-Mixpanel D3).
//
// Outside this file: zero direct Mixpanel usage; all calls go through AnalyticsService.
//
// Swift 6 note:
//   MixpanelInstance is not Sendable (Swift-5 SDK, uses DispatchQueue internally).
//   We mark this wrapper @unchecked Sendable and accept the responsibility:
//   every call goes to Mixpanel's own track/identify APIs, which are thread-safe
//   via their internal trackingQueue. We never mutate shared state ourselves.
//
// Token is read from AnalyticsConfiguration (auto-generated by the
// "Generate Analytics Token" build phase from Config/Secrets.xcconfig).

import Mixpanel
import Foundation

final class MixpanelAnalytics: AnalyticsService, @unchecked Sendable {

    // MARK: - Singleton

    static let shared = MixpanelAnalytics()

    // MARK: - Init

    private init() {
        let token = AnalyticsConfiguration.mixpanelToken
        guard !token.isEmpty else {
            print("[MixpanelAnalytics] ⚠️ Token empty — fill MIXPANEL_DEV_TOKEN in Config/Secrets.xcconfig and rebuild")
            return
        }
        // trackAutomaticEvents: false — we own the full event taxonomy (spec §Event Taxonomy).
        Mixpanel.initialize(token: token, trackAutomaticEvents: false)

        #if DEBUG
        // Spec §Тестування до TestFlight: log every event to Xcode console in DEBUG.
        Mixpanel.mainInstance().loggingEnabled = true
        #endif
        // Release builds: no opt-out call here. Consent is gated at the SourceBibleApp
        // level — NoopAnalytics is used when analyticsEnabled is OFF, so this class
        // is only instantiated and called when the user has consented.
    }

    // MARK: - AnalyticsService

    func track(_ event: AnalyticsEvent) {
        let (name, props) = event.nameAndProperties
        let mpProps = props.compactMapValues { $0 as? MixpanelType }
        Mixpanel.mainInstance().track(event: name, properties: mpProps)

        #if DEBUG
        // Spec §Тестування до TestFlight: flush immediately in DEBUG so events
        // appear in Mixpanel Live / Events within seconds (no batch wait).
        Mixpanel.mainInstance().flush()
        #endif
    }

    func identify(distinctId: String) {
        Mixpanel.mainInstance().identify(distinctId: distinctId)
    }

    func flush() {
        Mixpanel.mainInstance().flush()
    }

    // MARK: - Helpers

    /// True when running from TestFlight (sandboxReceipt) or Simulator.
    static var isTestFlight: Bool {
        #if targetEnvironment(simulator)
        return true
        #else
        return Bundle.main.appStoreReceiptURL?.lastPathComponent == "sandboxReceipt"
        #endif
    }
}
