#!/usr/bin/env python3
"""
generate_nasb_override.py
Generates NASBExtendedOverride.swift — maps NASB proprietary Strong's numbers
(H9000+) to Macula base numbers via gloss matching.

Usage:
    python3 scripts/generate_nasb_override.py [path/to/sourcebible.db]

Output:
    SourceBible/Services/NASBExtendedOverride.swift
"""
import sqlite3, re, sys, os
from collections import defaultdict

DB_PATH = sys.argv[1] if len(sys.argv) > 1 else 'SourceBible/Resources/sourcebible.db'
OUT_PATH = 'SourceBible/Services/NASBExtendedOverride.swift'

conn = sqlite3.connect(DB_PATH)
books = conn.execute("SELECT id, name_en, num FROM book ORDER BY num").fetchall()

def base_num(sid):
    return ''.join(c for c in sid.lstrip('HG') if c.isdigit())

def normalize(s):
    s = re.sub(r'[^a-z ]', '', s.lower())
    s = re.sub(r'(ing|ed|s|ly|er|est|ion|tion|ness)\b', '', s)
    return s.strip()

def word_overlap(a, b):
    wa = set(normalize(a).split())
    wb = set(normalize(b).split())
    return len(wa & wb)

override_map = {}
confidence = {}
total_unique_ext = set()

for book_id, book_name, _ in books:
    nasb_rows = conn.execute(
        "SELECT chapter, verse, text FROM verse WHERE book_id=? AND translation='NASB'",
        (book_id,)).fetchall()

    macula_by_verse = defaultdict(list)
    for ch, v, sid, morph, gloss in conn.execute(
        "SELECT chapter, verse, strongs_id, morph, gloss_macula FROM word WHERE book_id=? AND strongs_id IS NOT NULL",
        (book_id,)):
        macula_by_verse[(ch, v)].append((sid, morph, gloss or ''))

    for ch, v, text in nasb_rows:
        all_nums = set(re.findall(r'<S>(\d+)</S>', text))
        regular = {n for n in all_nums if int(n) <= 8674}
        extended = {n for n in all_nums if int(n) > 8674}
        if not extended:
            continue

        total_unique_ext.update(extended)
        macula_words = macula_by_verse.get((ch, v), [])

        segments = re.split(r'<S>(\d+)</S>', text)
        nasb_ext_context = {}
        for i in range(1, len(segments), 2):
            num = segments[i]
            if int(num) > 8674:
                raw_context = segments[i-1] if i > 0 else ''
                clean = re.sub(r'<[^>]+>', '', raw_context)
                words = clean.strip().split()
                nasb_ext_context[num] = ' '.join(words[-3:]) if words else ''

        for ext_num in extended:
            if ext_num in override_map:
                continue

            nasb_ctx = nasb_ext_context.get(ext_num, '').lower()

            candidates = []
            for sid, morph, gloss in macula_words:
                b = base_num(sid)
                if b not in regular:
                    candidates.append((b, sid, morph, gloss))

            seen = set()
            unique_cands = []
            for b, sid, morph, gloss in candidates:
                if b not in seen:
                    seen.add(b)
                    unique_cands.append((b, sid, morph, gloss))

            if not unique_cands:
                continue

            if len(unique_cands) == 1:
                override_map[ext_num] = unique_cands[0][0]
                confidence[ext_num] = 'direct'
                continue

            if nasb_ctx:
                scored = sorted(
                    [(word_overlap(nasb_ctx, g), b, sid, m, g) for b, sid, m, g in unique_cands],
                    reverse=True
                )
                best = scored[0]
                if best[0] > 0:
                    tie = len(scored) > 1 and scored[0][0] == scored[1][0]
                    override_map[ext_num] = best[1]
                    confidence[ext_num] = 'gloss_tie' if tie else 'gloss'

total = len(total_unique_ext)
mapped = len(override_map)

lines = [
    '// Auto-generated by scripts/generate_nasb_override.py — do not edit manually.',
    '// Maps NASB proprietary extended Strong\'s numbers (H9000+) to Macula base numbers.',
    '// Used in ReaderViewModel.isClickable() to handle cases where NASB uses its own',
    '// numbering system for words that Macula tags with standard Strong\'s sub-entries.',
    f'// Entries: {mapped} of {total} unique extended numbers resolved ({100*mapped//total}%).',
    '// Remaining unresolved: ReaderViewModel.isClickable() falls back to morph-based check.',
    '',
    'extension ReaderViewModel {',
    '    /// NASB extended number (numeric string) → Macula Strong\'s base number.',
    '    /// e.g. "9238" → "3887"  (H9238 לֵצִים in NASB = H3887a in Macula)',
    '    static let nasbExtendedOverride: [String: String] = [',
]
for ext_num, mac_base in sorted(override_map.items(), key=lambda x: int(x[0])):
    conf = confidence.get(ext_num, '?')
    lines.append(f'        "{ext_num}": "{mac_base}",  // {conf}')
lines += ['    ]', '}', '']

with open(OUT_PATH, 'w') as f:
    f.write('\n'.join(lines))

print(f"Written {OUT_PATH} — {mapped}/{total} entries ({100*mapped//total}%)")
